### ISSUE TITLE
[RC 5.1] - DanaR Pump Settings display time format and temp target issue

### ISSUE THREAD

**Issue by Melcp** [MilosKozak/AndroidAPS#1258]
Hi

1) When I change the "Display Time Format" in the "DanaR Pump Settings" menu from 12 to 24 hours (the button goes green and "24H" is highlighted), the actual time format on the pump changes to 12 hours. Basically the button in the menu does the reverse of what it is meant to, if it says 12 hour format the pump uses the 24 hour time format and vice versa. 

2) I noticed that someone else had posted about the issue with default temp targets. If I activate the default exercise temp target from the main menu it tells me that instead of setting the BG target to 6.5mmol it is set to 0.4mmol i.e to reverts to mg/dl. Jotomo suggested setting a default temp target in preferences to deal with this issue but my default exercise temp target in preferences is already set to 6.5mmol. 

Thanks for everything else though. Liking RC5.1 an awful lot.

**Comment by MilosKozak** [comment]
both is fixed in dev now

**Comment by Mackwe** [comment]
Issue number 2 still exist in Dev as of a few hours ago. If Default Temp Targets are set in mg/dl, it works. But everything else is mmol/l in my installation, so I'd like to have mmol there as well. :-)

**Comment by Mackwe** [comment]
Clarification: When i.e Hypo is set through the NewCarbsDialog, it works. When chosen by long-press target (upper right corner) -> Hypo, it still has the mg/dl conversion issue.
