### ISSUE TITLE
[2.4-RC1] Automation task: location based rule not triggered when accessing WLAN

### ISSUE THREAD

**Issue by chriddetyp1** [MilosKozak/AndroidAPS#2025]
Hi! 
I tried to set up rule when accessing a Wifi Hotspot which triggers a Temp Target. Unfortunately it´s not trigerred. Tried it it with different hotspots to avoid typo errors with no luck. Switched Wifi reception on/off, rebooted phone and waited for new BG readings but rule is not executed. Also switched in the config builder the location service between "network location" and "passive location" with no luck. 

Set up:
Phone: Oneplus 6 (Oxygen 9.0.8), Android 9, G5

AAPS 2.4-RC1
Build: d4f393775-2019.09.02-13:16
Flavor: fullrelease
Engineering mode enabled

Reporting bugs
--------------
- **Note the precise time the problem occurred** and describe the circumstances and steps that caused
  the problem
- Note the Build version (found in the About dialog in the app, when pressing the three dots in the
  upper-right corner).
- Obtain the app's log files, which can be found on the phone in
  _/storage/emulated/0/Android/data/info.nightscout.androidaps/_
  See https://github.com/MilosKozak/AndroidAPS/wiki/Accessing-logfiles
- Open an issue at https://github.com/MilosKozak/AndroidAPS/issues/new
![Screenshot_20190905-140229__01](https://user-images.githubusercontent.com/32034441/64341980-d63a8600-cfe9-11e9-964c-2f4a88104181.jpg)

[AndroidAPS_LOG_1567686560658.log.zip](https://github.com/MilosKozak/AndroidAPS/files/3579289/AndroidAPS_LOG_1567686560658.log.zip)

**Comment by chriddetyp1** [comment]
Hej, I also adjusted (this rule) the Wifi SSID in favor for a fictious (non existent) Wifi SSid with the condition "is not avaliable" with the result that the rule also will not be triggered. May be this leads somewhere to review the coding?

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/9e4ddbf8fc789a20b5d4f342390615740e9ea827

**Comment by chriddetyp1** [comment]
Hi! 
I am on Build d4f393775-2019.09.22-18:23 and I am still not able to create a successful automation rule with Wifi SSid. Was anyone else lucky?
