### ISSUE TITLE
Calulator "Corr" "+" button issue

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2066]
Little bug in Calculator with "Corr" + button : 

if Corr field is empty and I press one time on + button, Corr value is set to 0.01

But when Corr value is set to 0.01, when I press on + button, Corr field is cleared and I have a message "Bolus constraint applied"
=> Corr can't be set from 0.02 to 0.04
Impossible from an empty "Corr field" to set a correction with a long press on + button

**Comment by MilosKozak** [comment]
this should be already fixed in dev

**Comment by Philoul** [comment]
the problem still exist in dev version...
"Bolus constraint applied" for each Corr between 0.02 and 0.04
