### ISSUE TITLE
[2.6 RC1] Profile switch freezes app

### ISSUE THREAD

**Issue by xJoe** [MilosKozak/AndroidAPS#2259]
Manual profile switch (pressing Button profile name on homescreen) freezes app after confirmation screen opened. Happens only with NS profile. No problem with local profile.

**Comment by MilosKozak** [comment]
can you provide logs after this happen.
i didn't notice this issue

**Comment by xJoe** [comment]
Happened monday evening but I cannot remember exact time. Would that be a problem?
Clone NS profiles to local profile after the app frooze several times. Just tried to reproduce the freezing switching back to NS profile. Was not able to reproduce.

**Comment by tanja3981** [comment]
Had the same problem at 12.44. Attached the log file. 
[AndroidAPS.log](https://github.com/MilosKozak/AndroidAPS/files/3960579/AndroidAPS.log)

**Comment by MilosKozak** [comment]
profile name was not grabbed from dialog properly
can you reproduce it?

**Comment by tanja3981** [comment]
@MilosKozak Yes, reproducible anytime as no profile switches are possible with the RC version. (Have to install release for profile switches...)

**Comment by tanja3981** [comment]
Tried to debug into the problem on my spare phone, where it problem also exists... The profileStore does indeed contain 4 profiles, one with the name of the selected profile. However, the 
profile = cachedObjects[profileName]
in line 46 does return a null object.

@MilosKozak Any ideas how/where I could dig deeper into this?

**Comment by MilosKozak** [comment]
can you paste the whole JSON?

**Comment by tanja3981** [comment]
If you mean the json of store variable, yes. See attached file.
[store.txt](https://github.com/MilosKozak/AndroidAPS/files/3964341/store.txt)

**Comment by MilosKozak** [comment]
there is no "units" inside profiles .... where is this json generated?

**Comment by tanja3981** [comment]
I don't know where it's generated.
It was entered on the Nightscout profile page and works fine with the current release (and those before) but not the RC.
Do you have any suggestions how it can be fixed?

**Comment by MilosKozak** [comment]
working on it

**Comment by MilosKozak** [comment]
resolved in https://github.com/MilosKozak/AndroidAPS/commit/8af8d584ebbfcbf5632fd3eed41b804c2d03a128

**Comment by tanja3981** [comment]
@MilosKozak 
Just build latest dev with the commit mentioned... 
Still hangs on profile changes, but with a different stacktrace:
20:47:07.511 [main] E/CORE: [MainApp.lambda$onCreate$0():143]: Uncaught exception crashing app
java.lang.NullPointerException: Attempt to invoke virtual method 'org.json.JSONObject info.nightscout.androidaps.data.Profile.getData()' on a null object reference
	at info.nightscout.androidaps.plugins.configBuilder.ProfileFunctions.prepareProfileSwitch(ProfileFunctions.java:164) ~[na:0.0]
	at info.nightscout.androidaps.plugins.configBuilder.ProfileFunctions.doProfileSwitch(ProfileFunctions.java:174) ~[na:0.0]
	at info.nightscout.androidaps.plugins.general.careportal.Dialogs.NewNSTreatmentDialog.createNSTreatment(NewNSTreatmentDialog.java:708) ~[na:0.0]
	at info.nightscout.androidaps.plugins.general.careportal.Dialogs.NewNSTreatmentDialog.lambda$confirmNSTreatmentCreation$2$NewNSTreatmentDialog(NewNSTreatmentDialog.java:698) ~[na:0.0]
	at info.nightscout.androidaps.plugins.general.careportal.Dialogs.-$$Lambda$NewNSTreatmentDialog$C8xuFOVq36IlyTUzDtnPw_bvipE.onClick(Unknown Source:4) ~[na:0.0]
	at androidx.appcompat.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:107) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:214) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:7356) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) ~[na:0.0]

**Comment by tanja3981** [comment]
Still exits in RC2.
Can someone reopen this issue?
@MilosKozak

**Comment by MilosKozak** [comment]
@tanja3981 can you debug this again?
profile = cachedObjects[profileName]
in line 46 does return a null object.

**Comment by tanja3981** [comment]
Yes, that's null.
Stepping forward, into the if (47), into first let (48), doing JsonHelper.safeGetStringAllowNull in line 50 but the second let is never entered -> null is returned by the function and assigned to profileJson in ProfileFunctions.prepareProfileSwitch to profileJson.


I was able to solve this by creating a brand new profile and entering manually all values, as copying the profile didn't add the unit field. I don't know if this is something we can tell users when the experience this problem in the upcoming release.

**Comment by MilosKozak** [comment]
@tanja3981 is there a way to reproduce this issue?

**Comment by tanja3981** [comment]
@MilosKozak Yes, I have the old dataset still in my mongo db any can, with an current timestamp, download it from ns anytime...
Shall I send it to you on slack?

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/034bf3ecd8ccb067e97a1c25d7fc9ac6f80d0180
thx @tanja3981

**Comment by tanja3981** [comment]
Working... 👍
Thanks a lot for your work!
