### ISSUE TITLE
Double SMBs being delivered

### ISSUE THREAD

**Issue by markorders** [MilosKozak/AndroidAPS#2443]
SMBs are being delivered twice on some occasions. I have observed the pump deliver the same SMB upon immediate completion of the first without waiting for new BG data. It shows up in Treatment tab and also Pump History too, and I've witnessed it happening on the pump.

The logs have been emailed containing one such instance occuring at 13:04, and 13:05 on 11/2/20 with an SMB of 0.6U, and it was observed happening at least three times on 10/2/20.

None of these events have caused a low blood sugar event, however I am not sure why this is happening. The Facebook group suggested logging this. I can provide more logs if required for the double SMB events of 10th Feb 2020.

Thank you.

I am using 2.5.1, a Dana RS, and a Xiaomi Note 7.

**Comment by MilosKozak** [comment]
are you able provide logs?

**Comment by markorders** [comment]
[AndroidAPS_LOG_1581427660421.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4199087/AndroidAPS_LOG_1581427660421.log.zip)

Here are the logs for the incident mentioned, and I can provide further logs if required of some similar occurances.

**Comment by markorders** [comment]
![Screenshot_2020-03-02-22-00-35-737_com facebook katana](https://user-images.githubusercontent.com/36668545/75722449-2319c380-5cd2-11ea-8d18-5bed7f3c9050.jpg)
![Screenshot_2020-03-02-22-06-23-645_info nightscout androidaps](https://user-images.githubusercontent.com/36668545/75722451-244af080-5cd2-11ea-8d86-8457c6b2177b.jpg)

**Comment by markorders** [comment]
I have reenabled SMBs and as you can see double SMBs are being delivered. I am observing them on the pump as being delivered.

**Comment by markorders** [comment]
[AndroidAPS_LOG_1583186952546.log.zip](https://github.com/MilosKozak/AndroidAPS/files/4278140/AndroidAPS_LOG_1583186952546.log.zip)

**Comment by MilosKozak** [comment]
good catch, never happened to me, but it was a bug
hopefully fixed by https://github.com/MilosKozak/AndroidAPS/commit/1e02773b71d0180bf30b6185c40b718ea268200f

**Comment by MilosKozak** [comment]
reopen if this reappear in next version

**Comment by CaroGo** [comment]
Could this issue be opened again, please? People are still having this issue....

**Comment by markorders** [comment]
Hello, I'm still seeing this in the latest version. I'm not sure how to reopen the issue. I'll provide further logs when I download them.

**Comment by markorders** [comment]
![95477097_10163532889785252_3564275582357209088_o](https://user-images.githubusercontent.com/36668545/81041173-0d2ca880-8ea5-11ea-9991-9e24b71df5f1.jpg)

**Comment by Pallesauka** [comment]
@TebbeUbben @MilosKozak this happened also to me running Dev 2.6.6. 
![Screenshot_20200524-094058__01](https://user-images.githubusercontent.com/34350745/82748531-d8748880-9da2-11ea-8f84-b6a2254eefca.jpg)

**Comment by MilosKozak** [comment]
provide logs

**Comment by MilosKozak** [comment]
what do you see delivered on pump?

**Comment by Pallesauka** [comment]
> provide logs

[AndroidAPS._2020-05-23_00-00-03_.26.zip](https://github.com/MilosKozak/AndroidAPS/files/4673140/AndroidAPS._2020-05-23_00-00-03_.26.zip)

**Comment by Pallesauka** [comment]
> what do you see delivered on pump?

Pump seems to have delivered 0.1u twice at 19.03 2020-05-23

**Comment by markorders** [comment]
> what do you see delivered on pump?

I can confirm the double boluses are being delivered by the pump. Confirmed visually and in pump history. They follow each other almost immediately

**Comment by MilosKozak** [comment]
I located the bug. It's rare because it's combination of many factors
* Automation with TT rules
* DanaRS pump
....
Finally the problem is that RS is processing commands faster than AAPS is processing data

**Comment by Pallesauka** [comment]
> I located the bug. It's rare because it's combination of many factors
> 
> * Automation with TT rules
> * DanaRS pump
>   ....
>   Finally the problem is that RS is processing commands faster than AAPS is processing data

Very good. This also happened for DanaR users like me where commands are not processed as quickly but hopefully this is solved too.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/c5aa12c5badb36d809e0e0c8c73228b49c7f65d2
