### ISSUE TITLE
[Dev 98af8531f] AndroidAPS not using for complete the language selected.

### ISSUE THREAD

**Issue by parapenT1sta** [MilosKozak/AndroidAPS#2570]
Smartphone: Realme X2 PRO with Realme UI 1.0 (Android 10)
Android OS Language: Portuguese (Portugal)
AndroidAPS Language: English

Issue: Half information is in English other half in Portuguese.

![Screenshot_2020-04-14-12-39-41-49_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/608650/79221684-2e721a00-7e4e-11ea-9d1b-5a69651ebfea.jpg)
![Screenshot_2020-04-14-12-42-57-71_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/608650/79221688-2fa34700-7e4e-11ea-81cc-f6c1e28216c1.jpg)
![Screenshot_2020-04-14-12-43-02-53_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/608650/79221691-2fa34700-7e4e-11ea-86f2-1f2e620cfee1.jpg)
![Screenshot_2020-04-14-12-43-08-20_3eaa31bb2c2a38a1c605d9dc918cf694](https://user-images.githubusercontent.com/608650/79221693-303bdd80-7e4e-11ea-8330-e68d840c8b33.jpg)

**Comment by Philoul** [comment]
Which AndroidAPS version do you have ?
There were language issues in 2.5 which are fixed in 2.6...

**Comment by parapenT1sta** [comment]
> Which AndroidAPS version do you have ?
> There were language issues in 2.5 which are fixed in 2.6...

As I wrote in the topic was using Dev with commit 98af8531f but still the same even on the newer versions.

**Comment by MilosKozak** [comment]
try Default language now
