### ISSUE TITLE
[2.7] ABS IOB lower than IOB

### ISSUE THREAD

**Issue by Philoul** [MilosKozak/AndroidAPS#2881]
I thought that the absolute curve includes basal rate so absolute value should be greater than the IOB value ... but as you can see in the curves below the absolute values ​​are much lower than IOB values ​​...

I misunderstood something ?

![IOB-ABS Compare](https://user-images.githubusercontent.com/52934600/89706392-753bd080-d965-11ea-9149-42c5d71ecc1b.jpg)

**Comment by reijoahola-nightscout** [comment]
I am also somewhat confused how it should work. When I tested this in my test system it looks like both normal basal and temp basal chasnges are not included in Absolute insulin. So the difference between IOB and ABS is that IOB includes temp basal changes.

**Comment by MilosKozak** [comment]
![image](https://user-images.githubusercontent.com/11146458/89777014-3e072400-db0b-11ea-9d79-425c0dfa8662.png)
it works like it should.
I need more info

**Comment by Philoul** [comment]
I wrote a message on Slack with more explains.
After code analysis, I think you only have Bolus IOB (including SMB) in ABS curve, so when you have long period with zero temp and SMB, ABS values are greater than IOB values (it was probably your case when you made your screenshot), but when you have high TBR for a long time then the ABS curve is lower (that's what happened when I made my screenshot...)

**Comment by reijoahola-nightscout** [comment]
For me this new feature Absolute Insulin (ABS) could be useful if it includes every type of insulin meaning also normal basal and TBR changes. That would mean that the difference between IOB and ABS is the normal basal. The name (Absolute Insulin) is also good for that kind of situation.

**Comment by MilosKozak** [comment]
fixed by https://github.com/MilosKozak/AndroidAPS/commit/b8327f6b3a7dc0bc09db858c677456d17c581630
2 bugs. my shame.
Thanks!

**Comment by Philoul** [comment]
Cool... I was not far
I found it because I'm diving into Iob calculation for autotune plugin... I still have some light gaps in my results.
