### ISSUE TITLE
False Alarm "zero value in profile"

### ISSUE THREAD

**Issue by gregorybel** [MilosKozak/AndroidAPS#605]
Hi,

aaps=b4998fe (combo branch)
NS=0.10.3-dev

Local Profile looks good (I think):

![2018-01-13 17 03 43](https://user-images.githubusercontent.com/24234385/34916409-2f4fd626-f938-11e7-88cb-bc0026ac6145.jpg)

But NS Treatment looks strange:

![2018-01-14 10 29 45](https://user-images.githubusercontent.com/24234385/34916377-e5ada3ae-f937-11e7-8df0-5da89eb927d6.jpg)

Could it the root cause for false alarm?

Thanks
Gregory

**Comment by MilosKozak** [comment]
on picture is another issue. this is solved by https://github.com/MilosKozak/AndroidAPS/commit/060895b33f4abbaaa8f6f0f32113dc1b152a1910 . you should see profile switch causing this message

**Comment by gregorybel** [comment]
thank you Milos! No more alarm.
But second image is still wrong, don't know if it is important?
